package application.Controller;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Label;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;

public class dashboardController {
	@FXML
	private Label employeeButtton;
	@FXML
	private AnchorPane rootPane;
	@FXML
	private Label billbutton;

	/**
	 * Event Listener on Label[employeeButtton].onMouseClicked.
	 * 
	 * @param event
	 *            object of class MouseEvent.
	 * @throws IOException
	 */
	@FXML
	public void employee(MouseEvent event) throws IOException {
		// TODO Autogenerated
		AnchorPane pane = FXMLLoader.load(getClass().getResource("/application/View/employeeList.fxml"));
		rootPane.getChildren().setAll(pane);

	}

	/**
	 * Event Listener on Label[billbutton].onMouseClicked.
	 * 
	 * @param event
	 *            object of class MouseEvent.
	 * @throws IOException
	 */
	@FXML
	void show(MouseEvent event) throws IOException {
		AnchorPane pane = FXMLLoader.load(getClass().getResource("/application/View/table.fxml"));
		rootPane.getChildren().setAll(pane);
	}
}
